project_id = "wuxnorpdjjukvrlckeex"

[functions.generate-playlist]
verify_jwt = false

[functions.search-youtube]
verify_jwt = false

[functions.search-youtube-multiple]
verify_jwt = false

[functions.search-lyrics]
verify_jwt = false